<h1 align=center> Numpy In Depth With Practical Example </h1>

**NumPy** (Numerical Python) is a fundamental package for scientific computing in Python. It provides support for arrays, matrices, and many mathematical functions to operate on these data structures.

![alt text](../Images/python/np.png)

### Installation 

In [1]:
!pip install numpy


[notice] A new release of pip is available: 24.1.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

print(np.__version__)

1.24.3


### 1. **Creating Arrays**

NumPy provides a powerful array object called ndarray. Arrays are homogeneous, meaning all elements have the same data type.

In [3]:
import numpy as np

# 1D array
arr1 = np.array([1, 2, 3, 4])
print("1D Array:", arr1)

# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

# 3D array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", arr3)

1D Array: [1 2 3 4]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### 2. **Array Attributes**

Understanding array attributes is essential for manipulating arrays effectively.

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array Shape:", arr.shape)  # Shape of the array
print("Array Dimensions:", arr.ndim)  # Number of dimensions
print("Array Size:", arr.size)  # Total number of elements
print("Array Data Type:", arr.dtype)  # Data type of elements

Array Shape: (2, 3)
Array Dimensions: 2
Array Size: 6
Array Data Type: int32


### 3. **Array Operations**

NumPy supports element-wise operations, which are much faster than Python loops.

In [5]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

print("Addition:", arr1 + arr2)
print("Multiplication:", arr1 * arr2)
print("Square Root:", np.sqrt(arr1))
print("Exponent:", np.exp(arr1))

Addition: [11 22 33 44]
Multiplication: [ 10  40  90 160]
Square Root: [1.         1.41421356 1.73205081 2.        ]
Exponent: [ 2.71828183  7.3890561  20.08553692 54.59815003]


### 4. **Indexing and Slicing**

NumPy arrays can be indexed and sliced in various ways.

In [6]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Accessing single element
print("Element at [1, 2]:", arr[1, 2])

# Slicing
print("Slicing rows 1 and 2, columns 1 and 2:\n", arr[1:3, 1:3])

# Boolean indexing
print("Elements greater than 5:", arr[arr > 5])

Element at [1, 2]: 7
Slicing rows 1 and 2, columns 1 and 2:
 [[ 6  7]
 [10 11]]
Elements greater than 5: [ 6  7  8  9 10 11 12]


### 5. **Broadcasting**

Broadcasting allows NumPy to perform operations on arrays of different shapes.

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
vec = np.array([1, 0, 1])

# Adding vector to each row of the matrix
result = arr + vec
print("Broadcasted Addition:\n", result)

Broadcasted Addition:
 [[2 2 4]
 [5 5 7]]


### 6. **Reshaping and Resizing**

You can change the shape of an array using `reshape` and `resize`.

In [12]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])


# Reshaping
reshaped = arr.reshape(4, 2)
print("Reshaped Array:\n", reshaped)

# Resizing
arr.resize(2, 2, refcheck=False)
print("Resized Array:\n", arr)

Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Resized Array:
 [[1 2]
 [3 4]]


### 7. **Statistical Operations**

NumPy provides many statistical functions like `mean`, `sum`, `min`, `max`, etc.

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Standard Deviation:", np.std(arr))

# Operations along an axis
print("Column-wise Sum:", np.sum(arr, axis=0))

Sum: 21
Mean: 3.5
Max: 6
Standard Deviation: 1.707825127659933
Column-wise Sum: [5 7 9]


### 8. **Linear Algebra Operations**

NumPy also provides a suite of linear algebra functions, such as dot products, matrix multiplications, etc.

In [14]:
# Dot product
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

dot_product = np.dot(arr1, arr2)
print("Dot Product:\n", dot_product)

# Determinant
det = np.linalg.det(arr1)
print("Determinant:", det)

Dot Product:
 [[19 22]
 [43 50]]
Determinant: -2.0000000000000004


### 9. **Random Numbers**

NumPy's `random` module allows generating random numbers, arrays, and performing operations like shuffling.

In [15]:
# Generating a random array
rand_arr = np.random.rand(3, 3)
print("Random Array:\n", rand_arr)

# Generating random integers
rand_ints = np.random.randint(1, 10, size=(3, 3))
print("Random Integers:\n", rand_ints)

# Shuffling an array
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print("Shuffled Array:", arr)

Random Array:
 [[0.88675288 0.34394356 0.54408289]
 [0.22077226 0.24598902 0.78553326]
 [0.84237563 0.69745981 0.59995327]]
Random Integers:
 [[7 2 2]
 [7 1 1]
 [2 6 6]]
Shuffled Array: [3 1 4 5 2]


### 10. **Saving and Loading Arrays**

NumPy allows you to save and load arrays to and from files.

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Saving array to a file
np.save('my_array.npy', arr)

# Loading array from a file
loaded_arr = np.load('my_array.npy')
print("Loaded Array:\n", loaded_arr)

Loaded Array:
 [[1 2 3]
 [4 5 6]]
